[project]
name = ""
version = "0.0.1"
requires-python = "~=3.12"
dependencies = [
    "ezgpx",
    "geojson-transformer>=0.0.7",
    "geopandas[all]>=1.1.1",
    "lxml>=6.0.0",
    "matplotlib",
    "polars",
]

[dependency-groups]
dev = []

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[tool.uv.workspace]
members = [
    "cdmx25",
]
